{% set name = "meos" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MobilityDB/MobilityDB/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 169f679f2715ea39ba22a6d85c9417e74e16fe43b963db4190f96157e7178491

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - proj
    - json-c
    - gsl
    - postgis
    - libcblas
    - libpq
    - geos
  run:
    - geos

test:
  commands:
    - test -f $PREFIX/lib/libmeos$SHLIB_EXT  # [unix]

about:
  summary: Mobility Engine, Open Source
  description: |
    MEOS (Mobility Engine, Open Source) is a C library and its associated API for manipulating temporal and 
    spatiotemporal data. It is the core component of MobilityDB, an open source geospatial trajectory data management & 
    analysis platform built on top of PostgreSQL and PostGIS.
  license: PostgreSQL
  license_file: LICENSE.txt
  home: https://www.libmeos.com/
  doc_url: https://www.libmeos.com/
  dev_url: https://github.com/MobilityDB/MobilityDB

extra:
  recipe-maintainers:
    - Diviloper
    - estebanzimanyi
